@baseUrl=http://127.0.0.1:4200
@magicToken=

### (Magic) Login
# TODO: fix error without body (global validation?)
# TODO: show in ui and send in email code
POST {{baseUrl}}/auth/magic HTTP/1.1
Content-Type: application/json

{"destination":"test@qurl.dev"}

### (Magic) Login callback (Check token in logs for dev env)
GET {{baseUrl}}/auth/magic?token={{magicToken}} HTTP/1.1
