@baseUrl=http://localhost:4200
@magicToken=

### (Magic) Login
POST {{baseUrl}}/auth/magic HTTP/1.1
Content-Type: application/json

{"destination":"test@qurl.dev"}

### (Magic) Login callback (Check token in logs for dev env)
GET {{baseUrl}}/auth/magic?token={{magicToken}} HTTP/1.1
